import { POSITION_BY_ID, SLOT, STAT, FORBIDDEN } from './statmap.js';

const g = (s, id) => Number(s?.[id] ?? 0);

/**
 * Score one player's raw stat dict under a league scoring config.
 *
 * This mirrors how ESPN actually scores, confirmed against the league's own scoringSettings:
 * every stat id has ONE point value that applies to all positions, plus an optional override
 * keyed by position - in practice only position 16 (D/ST). There is no per-position branching.
 * That matters: stat 109 (tackles) is worth 1 point to EVERY position and 0 only to D/ST, so a
 * quarterback's two incidental tackles really do score, and Travis Hunter earns both his
 * receiving line and his 62 tackles.
 *
 * Configs generated by scripts/make-league-config.js use `scoring.all` / `scoring.dst`.
 * Hand-written configs using the older grouped shape still work.
 */
export function scoreStats(stats, pos, cfg, slots = null) {
  if (!stats) return 0;
  const sc = cfg.scoring;
  let pts = 0;
  const add = (group) => {
    if (!group) return;
    for (const [id, mult] of Object.entries(group)) {
      if (id.startsWith('_')) continue;
      if (FORBIDDEN.has(id)) continue;           // guard rail against double-count
      pts += g(stats, id) * mult;
    }
  };

  if (sc.all) {                                   // ESPN-derived flat form
    add(pos === 'DST' ? sc.dst : sc.all);
    return pts;
  }

  // legacy grouped form
  if (pos === 'K') { add(sc.kicking); return pts; }
  if (pos === 'DST') { add(sc.dst); add(sc.dstBrackets); return pts; }
  if (cfg.roster.dpEligible.includes(pos)) { add(sc.idp); return pts; }
  add(sc.passing); add(sc.rushing); add(sc.receiving); add(sc.misc);
  if (slots?.includes(SLOT.DP)) {
    for (const [id, mult] of Object.entries(sc.idp)) {
      if (id.startsWith('_') || FORBIDDEN.has(id)) continue;
      if (sc.misc[id] != null) continue;
      pts += g(stats, id) * mult;
    }
  }
  return pts;
}

/**
 * Kept as a no-op shim: D/ST points-allowed and yards-allowed are now scored directly
 * from ESPN's own bracket-count stat ids inside scoreStats(), which is exact rather than
 * an approximation rebuilt from weekly totals. Both bracket families sum to exactly 17.
 */
export function scoreDstBrackets() { return 0; }

/**
 * Replacement level: the points you can still get at a position for free.
 *
 * Two baselines, and the choice matters more than it looks. The STARTER boundary (RB24 + flex
 * absorption, QB12, K12...) only accounts for ~120 players, but 192 are actually drafted. Since
 * roughly 12 kickers and 12 defenses go either way, but ~42 RBs and ~54 WRs go, a starter
 * baseline leaves K and D/ST replacement untouched while overstating what's freely available at
 * RB/WR/TE/QB - i.e. it systematically inflates kickers and defenses against skill players.
 *
 * POSTDRAFT (default) uses the count actually drafted at each position, measured from the mock
 * sweep. Effect on top-of-position VORP: QB 93 -> 169, RB 179 -> 238, WR 142 -> 180, TE 79 -> 121,
 * K and D/ST unchanged. That is the bias being removed.
 */
export function replacementLevels(players, cfg) {
  const T = cfg.teams, st = cfg.roster.starters, flexElig = cfg.roster.flexEligible;
  const byPos = {};
  for (const p of players) (byPos[p.pos] ||= []).push(p);
  for (const k in byPos) byPos[k].sort((a, b) => b.pts - a.pts);

  const counts = cfg.roster.draftedCounts;
  if ((cfg.roster.replacementMode ?? 'postdraft') === 'postdraft' && counts) {
    const levels = {};
    const idpPool = cfg.roster.dpEligible.flatMap(p => byPos[p] || []).sort((a, b) => b.pts - a.pts);
    for (const pos of Object.keys(byPos)) {
      if (cfg.roster.dpEligible.includes(pos)) {
        levels[pos] = idpPool[counts.IDP ?? 24]?.pts ?? idpPool[idpPool.length - 1]?.pts ?? 0;
        continue;
      }
      const arr = byPos[pos];
      const n = counts[pos];
      levels[pos] = n == null ? (arr[arr.length - 1]?.pts ?? 0)
        : (arr[n]?.pts ?? arr[arr.length - 1]?.pts ?? 0);
    }
    return { levels, absorbed: {}, dpReplacementRank: counts.IDP ?? 24, mode: 'postdraft' };
  }

  // 1. lock in each position's dedicated starters
  const dedicated = {};
  for (const [pos, n] of Object.entries(st)) {
    if (pos === 'FLEX' || pos === 'DP') continue;
    dedicated[pos] = n * T;
  }
  // 2. the flex pool: best remaining among flex-eligible positions
  const pool = [];
  for (const pos of flexElig) pool.push(...(byPos[pos] || []).slice(dedicated[pos] || 0));
  pool.sort((a, b) => b.pts - a.pts);
  const flexN = (st.FLEX || 0) * T;
  const absorbed = {};
  for (const p of pool.slice(0, flexN)) absorbed[p.pos] = (absorbed[p.pos] || 0) + 1;

  // 3. DP draws from every IDP position at once
  const dpPool = [];
  for (const pos of cfg.roster.dpEligible) dpPool.push(...(byPos[pos] || []));
  dpPool.sort((a, b) => b.pts - a.pts);
  const dpN = (st.DP || 0) * T;

  const levels = {};
  for (const pos of Object.keys(byPos)) {
    const arr = byPos[pos];
    let idx;
    if (cfg.roster.dpEligible.includes(pos)) {
      // replacement for an IDP = the best IDP left after all DP slots are filled
      const cut = dpPool[dpN];                        // first unrostered IDP overall
      levels[pos] = cut ? cut.pts : 0;
      continue;
    }
    idx = (dedicated[pos] || 0) + (absorbed[pos] || 0);
    levels[pos] = arr[idx]?.pts ?? arr[arr.length - 1]?.pts ?? 0;
  }
  return { levels, absorbed, dpReplacementRank: dpN };
}

/**
 * ESPN's averageDraftPosition is CENSORED: below is real market data, but past roughly pick 158
 * it collapses into synthetic filler - on the 2026 board, 757 of 1232 players sit at ~170.0.
 * Treating that as real makes every late-round survival number nonsense, so anything at or past
 * the threshold is treated as "no ADP" and ordered by projected value instead.
 */
export function isCensoredAdp(adp, cfg) {
  const t = cfg?.tuning?.adpCensorFrom ?? 158;
  return adp == null || adp >= t;
}

/**
 * P(each player is still available at pick `target`), for a whole pool at once.
 *
 * A per-player normal CDF on raw ADP is not budget-consistent: summed over the pool it predicted
 * 728 players taken in a 15-pick window. This model is consistent by construction - it ranks the
 * pool by draft desirability and applies a logistic centred on the number of picks that will
 * actually happen, then normalises so expected removals equal that number exactly.
 *
 * Returns a Map of player id -> survival probability in [0,1].
 */
/**
 * OPPONENT-AWARE survival. Instead of asking "who does the market take next", ask, for each of
 * the specific picks between now and my next turn, "what would THAT team take, given the roster
 * it has actually built".
 *
 * Budget consistency falls out for free here: every pick removes exactly one player, so the
 * expected number of removals over the window is the number of picks in it, by construction -
 * no normalisation step, unlike the market-only curve below.
 *
 * `upcoming` is [{ team, round }] for each pick in the window, in order.
 * `rostersByTeam` maps a draft slot to that team's drafted players.
 * `needFn(player, roster, round)` returns a desirability multiplier for that team - it is passed
 * in so this module keeps no dependency on the guardrail logic in recommend.js.
 */
export function survivalCurveOpponentAware({
  available, upcoming, rostersByTeam, cfg, needFn, poolSize = 160, currentPick = null,
}) {
  const out = new Map();
  for (const p of available) out.set(p.id, 1);
  if (!upcoming?.length) return out;

  // Only realistic candidates matter. Anything past the ADP censor is effectively never taken
  // inside a short window, and including 1000 of them just dilutes the softmax.
  const pool = [...available].sort((a, b) => {
    const ca = isCensoredAdp(a.adp, cfg), cb = isCensoredAdp(b.adp, cfg);
    if (ca !== cb) return ca ? 1 : -1;
    if (!ca) return a.adp - b.adp;
    return (b.pts ?? 0) - (a.pts ?? 0);
  }).slice(0, poolSize);

  // The CALIBRATED market curve is the baseline. It carries real per-player ADP variance from
  // 8,104 drafts, and opponent information is only allowed to move a player RELATIVE to it.
  //
  // The first version of this ignored that and built its own prior, exp(-rank/tau). It was badly
  // wrong exactly where it matters: Jonathan Taylor (ADP 7.5, stdev 1.7) came out 35% to survive
  // nine picks when the truth is nearer 0-2%, because an exponential in RANK cannot express a
  // 1.7-pick standard deviation. That number is rendered in the UI and read under a 30-second
  // clock, so a miscalibrated one is worse than having no model at all.
  //
  // Opponent need now enters as a multiplicative adjustment to each player's HAZARD, -ln(s),
  // which is the quantity that genuinely adds across picks:
  //
  //     survival_opponent = survival_market ^ (need_player / need_average)
  //
  // A player the upcoming teams want more than average has his hazard scaled up and survives
  // less; one they want less survives longer. When need is flat the ratio is exactly 1 and this
  // reproduces the market curve to the digit.
  const market = survivalCurve(available, upcoming.length, cfg, currentPick);
  const needOf = pool.map(p => {
    let s = 0;
    for (const { team, round } of upcoming) {
      s += needFn ? needFn(p, rostersByTeam?.[team] || [], round, team) : 1;
    }
    return s / upcoming.length;
  });
  const meanNeed = needOf.reduce((a, b) => a + b, 0) / (needOf.length || 1);

  // Only adjust where the market is actually blind.
  //
  // For a player with real consensus ADP the market curve already encodes 8,104 drafts' worth of
  // information, and a paired A/B over 36 drafts said layering opponent need on top of that costs
  // about 3 points (t = -1.78, 6 better / 14 worse). But FFC publishes no ADP for defensive
  // players at all - every IDP sits at the censor value, so the market curve is guessing there,
  // while we genuinely know which teams have already taken their DP. Same for a deep bench with
  // no ADP. So: trust the market where it has data, use opponent need where it does not.
  const adjustable = pool.map(p => isCensoredAdp(p.adp, cfg));
  const alive = pool.map((p, i) => {
    const s = Math.min(0.999999, Math.max(1e-9, market.get(p.id) ?? 1));
    if (!adjustable[i]) return s;
    const ratio = meanNeed > 0 ? needOf[i] / meanNeed : 1;
    return Math.pow(s, ratio);
  });

  // Re-impose the pick budget: the reweighting shifts hazard between players, which can move the
  // total slightly. Rescaling in log space keeps the relative ordering that carries the signal.
  const W = upcoming.length;
  const baseline = pool.reduce((a, p) => a + (1 - (market.get(p.id) ?? 1)), 0);
  const target = Math.min(W, baseline);
  let k = 1;
  for (let iter = 0; iter < 40; iter++) {
    let tot = 0;
    for (let i = 0; i < pool.length; i++) tot += 1 - Math.pow(alive[i], k);
    if (Math.abs(tot - target) < 0.01 || tot >= pool.length) break;
    k *= Math.max(0.5, Math.min(2, target / Math.max(tot, 1e-9)));
  }
  pool.forEach((p, i) => out.set(p.id, Math.max(0, Math.min(1, Math.pow(alive[i], k)))));
  return out;
}

export function survivalCurve(available, picksInWindow, cfg, currentPick = null) {
  const out = new Map();
  const W = Math.max(0, picksInWindow);
  if (!available.length) return out;
  if (W === 0) { for (const p of available) out.set(p.id, 1); return out; }

  // Rank the pool the way the room will actually draft: real ADP first, then by value.
  const ranked = [...available].sort((a, b) => {
    const ca = isCensoredAdp(a.adp, cfg), cb = isCensoredAdp(b.adp, cfg);
    if (ca !== cb) return ca ? 1 : -1;                       // real ADP always ahead of censored
    if (!ca) return a.adp - b.adp;
    return (b.pts ?? 0) - (a.pts ?? 0);                      // censored: best projection goes first
  });

  // Rank-based logistic: the player ranked W-th among what is left is a coin flip to be gone.
  const s = Math.max(1.8, (cfg?.tuning?.survivalNoise ?? 0.16) * W + 1.2);
  const target = currentPick != null ? currentPick + W : null;

  const takeRaw = ranked.map((p, i) => {
    const rankTake = 1 / (1 + Math.exp((i + 1 - W) / s));
    // Where FantasyFootballCalculator gives a REAL per-player ADP standard deviation (from 8k
    // mock drafts), use it: a wide-variance player genuinely has a flatter survival curve than
    // rank alone implies. Blend rather than replace, since ADP is league-type specific.
    if (target != null && p.adpStdev > 0 && !isCensoredAdp(p.adp, cfg)) {
      const adpTake = normCdf((target - p.adp) / Math.max(1, p.adpStdev));
      return 0.5 * rankTake + 0.5 * adpTake;
    }
    return rankTake;
  });

  // Normalise so expected removals == W exactly, keeping every probability in [0,1].
  const sum = takeRaw.reduce((a, b) => a + b, 0);
  let k = sum > 0 ? W / sum : 0;
  for (let iter = 0; iter < 40; iter++) {
    let tot = 0;
    for (const t of takeRaw) tot += Math.min(1, k * t);
    if (Math.abs(tot - W) < 0.01 || tot >= available.length) break;
    k *= W / Math.max(tot, 1e-9);
  }
  ranked.forEach((p, i) => out.set(p.id, 1 - Math.min(1, k * takeRaw[i])));
  return out;
}

/** Single-player fallback, used only where a whole-pool curve is unavailable. */
export function survivalProb(adp, target, sd) {
  if (!adp) return 0.15;
  const z = (target - adp) / (sd || adpSd(adp));
  return 1 - normCdf(z);
}
export function adpSd(adp) { return Math.max(2.5, 0.42 * Math.pow(adp, 0.82)); }
function normCdf(z) {
  const t = 1 / (1 + 0.2316419 * Math.abs(z));
  const d = 0.3989423 * Math.exp(-z * z / 2);
  let p = d * t * (0.3193815 + t * (-0.3565638 + t * (1.781478 + t * (-1.821256 + t * 1.330274))));
  return z > 0 ? 1 - p : p;
}

/** k-means style 1-D tiering on projected points within a position. */
export function tierize(sorted, k) {
  if (sorted.length <= k) return sorted.map((_, i) => i + 1);
  const vals = sorted.map(p => p.pts);
  let cents = Array.from({ length: k }, (_, i) => vals[Math.floor(i * (vals.length - 1) / (k - 1))]);
  let assign = new Array(vals.length).fill(0);
  for (let iter = 0; iter < 40; iter++) {
    let changed = false;
    for (let i = 0; i < vals.length; i++) {
      let best = 0, bd = Infinity;
      for (let c = 0; c < k; c++) { const d = Math.abs(vals[i] - cents[c]); if (d < bd) { bd = d; best = c; } }
      if (assign[i] !== best) { assign[i] = best; changed = true; }
    }
    for (let c = 0; c < k; c++) {
      const m = vals.filter((_, i) => assign[i] === c);
      if (m.length) cents[c] = m.reduce((a, b) => a + b, 0) / m.length;
    }
    if (!changed) break;
  }
  // relabel so tier 1 = best, and force monotonic non-decreasing down the sorted list
  const seen = new Map(); let next = 1;
  return assign.map(a => { if (!seen.has(a)) seen.set(a, next++); return seen.get(a); })
               .map((t, i, arr) => (i ? Math.max(t, arr[i - 1]) : t));
}
